### ISSUE TITLE
"Adding a Model" vignette

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalcasting#113]
I'm currently working through the process of trying to add a new model, and getting confused by the specific implementation steps.

One of the main challenges with documentation is that `portalcasting` has (at least) 2 audiences:
  1. the people who are running the Portal Forecasting website within the lab and need to know how the infrastructure is connected
  2. contributors / end-users of portalcasting who may want to run the models on different subsets of the code or add new models.

For 2. as @gmyenni put it, "the process of adding a new model should be plug-and-play", but it's not clear that this is the case right now, and the directions for adding a new model aren't quite at that step yet? (or at least, the "Adding a Model" vignette does not clarify the steps to me)

As a basic example, the vignette starts by mentioning a `data/` and `models/` subdirectory, but they don't exist as part of the repo. (and they should be created through the `setup_dir()` function)

So, I think the higher-level organization of the vignette should be:
* (assume installation of the package and dependencies)
* set up the portalcasting folders and data locally
* example for adding a new model to read in data and make forecasts
* running the new model locally (ideally, without having to run *all* of the models in portalcasting -- not sure how much of this configuration should be done at this step or is part of the portalcasting codebase to be setup earlier, e.g. when setting up the folders)
* steps for moving the model files into the portalcasting codebase (as a PR, etc.)

**Comment by ha0ye** [comment]
I've started an example of a portalcasting sandbox at weecology/portalcasting-example with the goal of documenting steps for using the package to develop new models and eventually contribute a PR to portalcasting.

**Comment by skmorgane** [comment]
I agree that this documentation could be improved and that right now the combined audience for the documentation (a super user vs. model contributors) makes communication a challenge. That said, it Is possible for a naive user (ie. me) to follow the existing documentation and get a model added to the package. But it is daunting and took effort to figure out where things are and what exactly Needed to be done. I also missed something the first time I tried. A good example or even a detailed checklist or flow chart might help  with communication!

**Comment by juniperlsimonis** [comment]
totes agree on all the fronts here! thanks much to both of you for feedback.
i've included in #129 substantial updates to the vignettes, including a breakdown of the 'adding a model/data' vignette into the 'work locally' and 'add to the production pipeline' components, as well as some nice checklists and tons of screenshots. 
i'd def up for feedback/edits on these, but i think the updated version addresses all these comments
