### ISSUE TITLE
Add ETS model

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalcasting#114]
Spin-up project for @skmorgane to learn portalcasting. ETS is a commonly used forecasting model.

**Comment by juniperlsimonis** [comment]
woo hoo!
one thing to note: the ESSS model is functionally an ETS model, so we've basically got that in the suite already. some easy-to-start-with alternatives that we don't have explicitly but could use are [1] a poisson seasonal model (like the negative binomial seasonal model nbsGARCH, but with a poisson response variable as is done in pevGARCH), [2] a naive random walk (https://rdrr.io/github/robjhyndman/forecast/man/naive.html)

**Comment by skmorgane** [comment]
The naive random walk sounds like fun. I'll close this issue and make a new one. Thanks!
