### ISSUE TITLE
Add simple EDM model

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalcasting#115]
Spin-up project for @ethanwhite to learn portalcasting. EDMs are a good data-driven starting point for forecasting.

**Comment by ha0ye** [comment]
Ongoing work to be done in the `EDM` branch, started by @ethanwhite; see #144 

- [ ] create demo EDM model and script
- [ ] check format for saved outputs:
    * what components are needed to support ensemble / evaluation?
    * what metadata / model params should be saved?
- [ ] add tests

**Comment by ha0ye** [comment]
Seems to be working. (i.e. the following code runs)
```r
library(portalcasting)
main <- tempdir()
setup_sandbox(main = main)
portalcast(main = main, models = "simplexEDM", verbose = TRUE)
```

**Comment by ha0ye** [comment]
-[ ] document rEDM in current_models vignette
-[ ] add rEDM ref to .bibtex file

**Comment by juniperlsimonis** [comment]
done with #141
