### ISSUE TITLE
Vignette order issue

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalcasting#120]
For the [howto vignette](https://weecology.github.io/portalcasting/articles/howto.html) if you follow along in the current order in the vignette, the cleanup_dir() command cleans out the species list which is needed in the plotting steps that follow, yielding an error (and no plots).  Here's the error:  cannot open file 'C:\Users\skmorgane\Documents\PortalData\Rodents\Portal_rodent_species.csv': No such file or directory. I had @ethanwhite confirm this happened for him as well.

We should either change the order in the vignette so that cleanup_dir() comes at the end of the document or change cleanup_dir() so that it leaves a copy of the file for the plot functions. If we leave the function cleanup_dir as is, we should warn users that they shouldn't until they are completely done.

**Comment by juniperlsimonis** [comment]
oh! gah i hadn't even thought of that. this is why having folks run through your documents as a new user would is v v helpful.

i think it makes intuitive sense to have the cleaning up at the end of the whole session anyway, so what are your thoughts on just moving that "Tidy up the temporary files" section down to the bottom of the vignette and then adding a statement about "this actually cleans stuff up, so don't do it until you're done"? (i can make those edits, just asking your opinion on them!)

**Comment by ethanwhite** [comment]
Sounds perfect!

**Comment by juniperlsimonis** [comment]
done in #129
