### ISSUE TITLE
`setup_sandbox` function

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#125]
i've decided it will be nice to have a version of the main `setup_dir()` function tailored to the sandbox situation (whereas `setup_dir()` is meant to work on the main pipeline with default settings, which makes it much easier to tinker with code within the package, we want a version of `setup_dir()` that makes it nice for a sandboxing user): `setup_sandbox()` 
as of now the only things that jump out to me as being needed in the sandbox that aren't being default done is the downloading of the historic forecasts: the historic covariate forecasts as well as the historic rodent forecasts are housed within the main forecasting repo, so that server doesn't need to spend time dowloading files and the default in the control lists is to not download them, although it's a simple toggle to do it. the way the current API is,  it's actually really easy to manage this, so i decided to jump for it and create `setup_sandbox()` .  it's basically a call to `setup_dir()` but with those download settings set to `TRUE`, and you would interact with it in the same way you would interact with `setup_dir()`.

at this point, it's easy to change other defaults, so i was wondering if folks who have interacted with `setup_dir()` in a sandbox setting (@ethanwhite @skmorgane @ha0ye? who else?) had any feedback/requests/suggestions for changed settings for sandboxing. this function is part of the in-works v0.9.0, but i wanted to get thoughts!

**Comment by ha0ye** [comment]
Nothing in particular comes to mind for me. It's been a while since I've played around with portalcasting, and I did not get very far on #113, which is only tangentially related anyway.

Thinking a bit about how best to address #119 and #120, I wonder how this can be handled at the setup stage? I don't think you want to create the R code for just some of the models, so this suggests maybe a template R script that has pre-set options for testing out the functionality, but doesn't do the full run, as for PortalPredictions.

**Comment by juniperlsimonis** [comment]
yeah, so i've worked out a system now where the `setup_` functions (it's actually the `fill_` functions, but that's under the hood) write out `.yaml` files of the control lists that allow the main `portalcast` function to have a much simpler API, where the user doesn't need to enter the same arguments into two functions.
in setting this up, however, it's clear that there will be a big distinction from a user perspective of arguments that are available at the top level and those that are tucked into the control lists. so i think my main question here for anyone who might want to just jump in and tinker with forecasting is "what do you really want to play with?" 
i get that folks want to control which models are run (and that's set up as the first argument in `portalcast`), but what else?

**Comment by ethanwhite** [comment]
Off the top of my head:

* species
* treatment
* forecast vs hindcast
* number of time steps to forecast
* covariates

**Comment by juniperlsimonis** [comment]
it totally makes sense to do species, but hilariously, it's currently coded as `drop_spp`, as in "drop species", or which species to drop from the list, rather than which species to include. so, that'll be getting updated.

**Comment by juniperlsimonis** [comment]
addressed with #129
