### ISSUE TITLE
Check if data version has changed before downloading

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalcasting#184]
Running `setup_production` (and probably other `setup_` functions downloads data even if that data hasn't changed. This isn't a big deal when developing interactively, but when testing code that runs `setup_*` as a first step it can slow down development. It might be worth seeing if there's a way to record the currently downloaded version (if there is one) and check to see if it has changed before doing the download.

**Comment by juniperlsimonis** [comment]
yeah, i totally get what you're saying here!
i think we need to chat to game plan the best approach for this. i was hamstrung before by some of the automated pipeline structure and my own knowledge when i built this part, and i've got a lot more skill on it, but need to get a walkthrough from you and/or henry so i know what the current state it. 
@henrykironde

**Comment by juniperlsimonis** [comment]
closing this as a similar issue to #195 
functionally the same idea: don't download unless needed
