### ISSUE TITLE
More informative warnings in setup_dir

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalcasting#194]
I usually get this warning in `setup_dir()` unless I delete everything.

```
1: In file.rename(unzip_destins$with_archive, unzip_destins$final) :
  cannot rename file '/Users/GlendaYenni/portalcasting/simple/tmp/PortalData/weecology-PortalData-e41cc9a/' to '/Users/GlendaYenni/portalcasting/simple/raw/PortalData', reason 'Directory not empty'
```
We could add a message to say something like 'Did you mean to use fill_dir()' or something?

**Comment by PrayasJ** [comment]
@juniperlsimonis I wasn't able to reproduce this issue, `setup_dir()` currently doesn't have any issue when it calls `create_dir()` related to renaming, I believe this has already been fixed.
