### ISSUE TITLE
Provide data for website generation in data folder, as much as possible

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalcasting#23]
As part of cleaning up website building in https://github.com/weecology/portalPredictions/issues/297 , let's see what we can provide (or have already provided but aren't using) at the setup_dir stage.

**Comment by juniperlsimonis** [comment]
what else do you think we could use/take advantage of?

**Comment by juniperlsimonis** [comment]
generally speaking, those data are available
if specifics are needed, issues can be created
[just cleaning up old issues]
