### ISSUE TITLE
portalcast requirement of downloading covariates data when running models that do not require it (e.g., AutoArima) is causing errors

### ISSUE THREAD

**Issue by patdumandan** [weecology/portalcasting#242]
I am getting the error message Error: covariates not available for requested end moon and lead time, when I change the end_moon value in portalcast. I did something like this:
`PP_data_controls <- rodents_control(name = "PP_controls", level = "Treatment",species="PP",interpolate=FALSE,
                                    treatment = "control", output="abundance", 
                                    arg_checks = FALSE)
AA_controls=model_control(name="AutoArima", data_sets = "PP_controls")
portalcast(main=main, models = "AutoArima",controls_model=AA_controls,update_prefab_models = TRUE,
           controls_rodents=PP_data_controls,arg_checks = FALSE, end_moon=500, verbose=T)`

Below is the script for the troubleshooting we did yesterday:
`main="sandbox_rep"

main=main; models = "AutoArima";controls_model=AA_controls;update_prefab_models = TRUE;
controls_rodents=PP_data_controls;arg_checks = FALSE; end_moon=500

#open portalcast function

  return_if_null(models)
  mainp <- main_path(main = main, arg_checks = arg_checks)
  verify(paths = mainp, arg_checks = arg_checks)
  portalcast_welcome(quiet = quiet, arg_checks = arg_checks)
  update_models(main = main, models = models, controls_model = controls_model, 
                update_prefab_models = update_prefab_models, quiet = quiet, 
                verbose = verbose, control_files = control_files, arg_checks = arg_checks)
  verify_models(main = main, models = models, quiet = quiet, 
                arg_checks = arg_checks)
  last <- last_moon(main = main, date = cast_date, arg_checks = arg_checks)
  end_moons <- ifnull(end_moons, last)
  nend_moons <- length(end_moons)
  for (i in 1:nend_moons) {
    cast(main = main, models = models, end_moon = end_moons[i], 
         start_moon = start_moon, lead_time = lead_time, confidence_level = confidence_level, 
         cast_date = cast_date, controls_model = controls_model, 
         controls_rodents = controls_rodents, control_files = control_files, 
         PortalData_version = PortalData_version, PortalData_source = PortalData_source, 
         portalPredictions_version = portalPredictions_version, 
         portalPredictions_source = portalPredictions_source, 
         climate_forecast_version = climate_forecast_version, 
         climate_forecast_source = climate_forecast_source, 
         quiet = quiet, verbose = verbose, arg_checks = arg_checks)
  }
  if (end_moons[nend_moons] != last) {
    data_resetting_message(bline = bline, quiet = quiet, 
                           arg_checks = arg_checks)
    fill_data(main = main, models = models, end_moon = NULL, 
              lead_time = lead_time, cast_date = cast_date, start_moon = start_moon, 
              confidence_level = confidence_level, controls_rodents = controls_rodents, 
              controls_model = controls_model, control_files = control_files, 
              quiet = !verbose, verbose = verbose, arg_checks = arg_checks)
  }
  portalcast_goodbye(bline = bline, quiet = quiet, arg_checks = arg_checks)
}

#open cast function

data_readying_message(end_moon = end_moon, bline = bline, 
                      quiet = quiet, arg_checks = arg_checks)
fill_data(main = main, models = models, end_moon = end_moon, 
          lead_time = lead_time, cast_date = cast_date, start_moon = start_moon, 
          confidence_level = confidence_level, controls_rodents = controls_rodents, 
          controls_model = controls_model, control_files = control_files, 
          quiet = !verbose, verbose = verbose, arg_checks = arg_checks)
clear_tmp(main = main, quiet = quiet, cleanup = control_files$cleanup, 
          arg_checks = arg_checks)
last <- last_moon(main = main, date = cast_date, arg_checks = arg_checks)
end_moon <- ifnull(end_moon, last)
models_running_message(end_moon = end_moon, bline = bline, 
                       quiet = quiet, arg_checks = arg_checks)
models_scripts <- models_to_cast(main = main, models = models, 
                                 arg_checks = arg_checks)
nmodels <- length(models)
for (i in 1:nmodels) {
  model <- models_scripts[i]
  model_running_message(model = model, quiet = quiet, arg_checks = arg_checks)
  run_status <- tryCatch(source(model), error = function(x) {
    NA
  })
  model_done_message(model = model, run_status = run_status, 
                     quiet = quiet, arg_checks = arg_checks)
}
clear_tmp(main = main, quiet = quiet, verbose = verbose, 
          cleanup = control_files$cleanup, arg_checks = arg_checks)
}
#error is coming from fill_data (end_moon)`

We got the same error message when we ran the line of code: fill_data in the cast function.

**Comment by juniperlsimonis** [comment]
should be good now!
