### ISSUE TITLE
GSoC Questions 

### ISSUE THREAD

**Issue by himanshu-02** [weecology/portalcasting#263]
Hi I am Himanshu, a GSoC aspirant who is interested in the project "High-performance parallel computing for model fitting and prediction in Portalcasting". 

I was referring to the [Getting Started](https://weecology.github.io/portalcasting/articles/getting_started.html) article  to set everything up which is when I encountered two errors.

1.  After running `devtools::install_github("weecology/portalcasting")` I got an error 
```configure: error: "automatic detection of JAGS failed. Please use pkg-config to locate the JAGS library. See the INSTALL file for details." ERROR: configuration failed for package ‘runjags’``` 

This was fixed by simply installing jags as a package ```sudo apt install jags``` for Debian/Ubuntu and then installing it in R ```install.packages("rjags")``` 

Maybe we could add this as a prerequisite in the getting started section. With some help, I am willing to add a PR for this. 

2. After running  `main <- "~/portalcast_directory"` and then `setup_production(main = main)` I got an error and warning

``` 
Error in Summary.factor(1:522, na.rm = FALSE) : 
  ‘max’ not meaningful for factors
In addition: Warning message:
In which(moons$newmoondate < cast_date) :
  Incompatible methods ("Ops.factor", "<.Date") for "<"
```  
I am relatively new to the codebase and need some guidance to resolve this issue 

Thanks!

**Comment by himanshu-02** [comment]
@juniperlsimonis could you help me out? As you're listed as the main mentor.

**Comment by henrykironde** [comment]
Hi @himanshu-02 thanks for this issue. Sorry we have been busy but you could improve the docs if you feel the description needs to be changed. I have tried to reproduce the error but I am not getting the same.
