### ISSUE TITLE
setup_production download timeout

### ISSUE THREAD

**Issue by PrayasJ** [weecology/portalcasting#282]
Upon running `setup_production()` on a new setup, it results in the following warning, for some reason, the forecast dated 2022-05-05 isn't being pulled.

```
Warning messages:
1: In download.file(url = zipball_url, destfile = temp, quiet = !verbose,  :
  URL 'https://codeload.github.com/weecology/portalPredictions/legacy.zip/refs/tags/2022-05-05': Timeout of 60 seconds was reached
2: In download_archive(main = main, resources_sub = settings$subs$resources,  :
  Archive could not be downloaded
```

**Comment by ethanwhite** [comment]
Hi @PrayasJ - this happened because it took a long time for some of the data to download and the download timed out. @juniperlsimonis has just implemented a fix that should prevent this from happening again. If you update your install with:

```R
devtools::install_github("weecology/portalcasting")
```

that should fix things.

**Comment by PrayasJ** [comment]
Oh alright. Got it. Yes, I saw that the default timeout was 60 seconds but couldn't find where it was being set. Thanks @ethanwhite for the explanation.

**Comment by ethanwhite** [comment]
Yeah, it wasn't exposed at the level of `setup_dir()` so you couldn't change it yourself, but @juniperlsimonis has also added it as an optional argument now so if you want or need to adjust it you can do that now by adding `download_timeout  = 600` to your `setup_dir()` command.
