### ISSUE TITLE
correct tsglm moving average

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#297]
should be 13, not 12, given lunar months

**Comment by juniperlsimonis** [comment]
wait, does this mean we should actually be predicting 13 steps ahead and not 12, then too? @skmorgane @ethanwhite

**Comment by ethanwhite** [comment]
I don't think it's a big deal either way, but yes since our goal is forecasting the next year we should convert the predictions to 13 new moons as well.

**Comment by juniperlsimonis** [comment]
done in #304
