### ISSUE TITLE
check contributors list

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#92]
please check the contribs list (basically copied over from portalPredictions) and let me know if i should make any changes

**Comment by ethanwhite** [comment]
@skmorgane and I went through the list this morning and the one person we thought would be worth considering adding here is Hao. He's been actively involved in the project for over a year and even though he may not have touched the code directly he's been involved in a lot of conversations and planning around it.

**Comment by juniperlsimonis** [comment]
totally agree on that
